### ISSUE TITLE
recaptcha problem

### ISSUE THREAD

**Issue by Afterinautas** [TheHellTower/Discord-Bot-List#108]
![image](https://github.com/TheHellTower/Discord-Bot-List/assets/144489368/75770eba-4d57-47e9-8e67-cfd9577b226c)
![image_2023-12-16_220324136](https://github.com/TheHellTower/Discord-Bot-List/assets/144489368/0a1a472d-d3b5-4ecf-a313-1b3e905a03dc)

good key but not working on localhost

**Comment by TheHellTower** [comment]
Invalid, follow the template.

https://github.com/TheHellTower/Discord-Bot-List/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=
