### ISSUE TITLE
A work flow to auto detect if the files are unformatted

### ISSUE THREAD

**Issue by Zaid-maker** [TheHellTower/Discord-Bot-List#34]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

A work flow which will detect if the files are unformatted then make them formatted using the prettier package and work flow.

**Comment by TheHellTower** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> A work flow which will detect if the files are unformatted then make them formatted using the prettier package and work flow.

Hey, sorry but the format is not respected !
