### ISSUE TITLE
enhancement: make adminUserIds in config a role & update other parts of code

### ISSUE THREAD

**Issue by idk-pixel** [TheHellTower/Discord-Bot-List#57]
**idea**: make adminUserIds in config a role & update other parts of code
this makes it so we dont have to configure it every time.

**Comment by TheHellTower** [comment]
> **idea**: make adminUserIds in config a role & update other parts of code this makes it so we dont have to configure it every time.

Hello,

Maybe it could be a nice idea but that's who I planned it: https://github.com/TheHellTower/Discord-Bot-List/issues/18
But right now I have to add rate-limits to the project when I will have a bit more time for this project, so I didn't think about a role at the end it would be using the database.

What do you think about it ?

Best Regards,
TheHellTower.

**Comment by TheHellTower** [comment]
@idk-pixel in 3 days this issue might get closed if no answer is posted.

**Comment by TheHellTower** [comment]
Left inactive.
