### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by idk-pixel** [TheHellTower/Discord-Bot-List#58]
bugs:

recaptcha: ~~because of camel case changes, there is a function in form.js called updateToken, we need to rename this update_token so we can use recaptcha to successfully submit/edit bots~~ (https://github.com/TheHellTower/Discord-Bot-List/commit/754387236ee4a6f3980acb00ae3076d12aedd6c0)

before widgeting bots: 
~~when we use the EMBED function on bots, if they dont  have a pfp, they throw an error instead of just sending an error that theres no PFP. we should make it so our entire server dosent crash when this happens. can easily be abused~~ (https://github.com/TheHellTower/Discord-Bot-List/commit/cc59a04eda631cb5d9fdaa782223b1d7dde76758)

~~throwing errors:
don't throw errors, log it and return an error that we can display~~

swals:

~~when there is an error, we use something called "Noty" which is not defined in any way, while if we use Swal.fire it would be defined, so we either need to make a class called 'Noty' or we can use the function we already have built in called Swal~~ (https://github.com/TheHellTower/Discord-Bot-List/commit/e31ecad07d9aad2b2eb8248ee7236e4bed591585)

**Comment by TheHellTower** [comment]
> bugs:
> 
> recaptcha: because of camel case changes, there is a function in form.js called updateToken, we need to rename this update_token so we can use recaptcha to successfully submit/edit bots
> 
> before widgeting bots: when we use the EMBED function on bots, if they dont have a pfp, they throw an error instead of just sending an error that theres no PFP. we should make it so our entire server dosent crash when this happens. can easily be abused
> 
> throwing errors: don't throw errors, log it and return an error that we can display
> 
> swals:
> 
> when there is an error, we use something called "Noty" which is not defined in any way, while if we use Swal.fire it would be defined, so we either need to make a class called 'Noty' or we can use the function we already have built in called Swal

Hello,

First of all thanks for your help, I will answer to each problem individually !

- ReCaptcha: No, just show me the place where the function name remain `update_token` so I can update it to `updateToken`, I didn't change to `camelCase` to get back that fast.

- Widget: Oh I didn't know ! I will fix this by adding a fallback to their "default" avatar(depend on the `discriminator`) !

- Throwing errors: Yeah I didn't make this code base, a cleanup will be needed anyway because a lot of things are bad in it such as code duplicate, etc...

- Swals: I don't get the problem `Swal` is working so can you elaborate ?

Best Regards,
TheHellTower.

**Comment by idk-pixel** [comment]
I'm saying to switch from Noty to swals
recaptcha: not sure if its because of the codebase, but im pretty sure google recaptcha isnt built on camelcase, so we have to do update_token, just for 1 function

**Comment by TheHellTower** [comment]
> I'm saying to switch from Noty to swals recaptcha: not sure if its because of the codebase, but im pretty sure google recaptcha isnt built on camelcase, so we have to do update_token, just for 1 function

Swals: Can you give me a context where `Noty` is `undefined` but needed ? I didn't see any issue with it when I published the updates.. And you are free to open a PR if you already thought about a way to solve this !

Recaptcha: Of so if it's a google function yeah then I will update this for sure I was thinking about a project function !

**Comment by TheHellTower** [comment]
updateToken = form.js function

**Comment by idk-pixel** [comment]
Ah, ok. So i see you have changed the re captcha thanks!

when you run into an error submitting bots , it uses Noty. When using this, via console noty isn’t defined. Therefore it cannot tell you an error (eg bot description too short) so it wont submit 

We can change this by migrating from Noty to swal.fire

**Comment by TheHellTower** [comment]
> Ah, ok. So i see you have changed the re captcha thanks!
> 
> when you run into an error submitting bots , it uses Noty. When using this, via console noty isn’t defined. Therefore it cannot tell you an error (eg bot description too short) so it wont submit
> 
> We can change this by migrating from Noty to swal.fire

Well ! You can either make a PR or if you have a bit of time tell me at which places Noty is used so I can get rid of it for Swal !
(Sorry I'm in-game right now)

**Comment by TheHellTower** [comment]
Ok so Noty file has been modified ! The hash wasn't matching anymore but I solved it by importing it locally :)

**Comment by TheHellTower** [comment]
Thrown errors are not in the user utilization case only when everything is loading or when either the `Command` or `Event` trying to be executed doesn't have any way to be ran so I leave it like it is.

**Comment by TheHellTower** [comment]
Everything is solved for the moment ! Feel free to refer to the commits hyper-links [here](https://github.com/TheHellTower/Discord-Bot-List/issues/58#issue-1739856254) to know how and the noAvatar is only a "temporary" solution since I need to do a big cleanup due to code duplicates.
