### ISSUE TITLE
like.ejs

### ISSUE THREAD

**Issue by BluAimz** [TheHellTower/Discord-Bot-List#61]
When I enter the /bots/like/ route, and the bot is nsfw, it gives this error:

ReferenceError: C:\Users\marti\Desktop\Discord-Bot-List-master\src\dynamic\like.ejs:13
    11|         <div class="like card">
    12|           <% if (bot.nsfw) { %>
 >> 13|             <img class="icon nsfw" src=<%= val.logo %> />
    14|           <% } else { %>
    15|             <img class="icon" src=<%= bot.logo %> />
    16|           <% } %>

val is not defined
    at eval ("C:\\Users\\marti\\Desktop\\Discord-Bot-List-master\\src\\dynamic\\like.ejs":21:26)
    at like (C:\Users\marti\Desktop\Discord-Bot-List-master\node_modules\ejs\lib\ejs.js:703:17)
    at tryHandleCache (C:\Users\marti\Desktop\Discord-Bot-List-master\node_modules\ejs\lib\ejs.js:274:36)
    at exports.renderFile [as engine] (C:\Users\marti\Desktop\Discord-Bot-List-master\node_modules\ejs\lib\ejs.js:491:10)
    at View.render (C:\Users\marti\Desktop\Discord-Bot-List-master\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\Users\marti\Desktop\Discord-Bot-List-master\node_modules\express\lib\application.js:657:10)
    at Function.render (C:\Users\marti\Desktop\Discord-Bot-List-master\node_modules\express\lib\application.js:609:3)
    at ServerResponse.render (C:\Users\marti\Desktop\Discord-Bot-List-master\node_modules\express\lib\response.js:1039:7)
    at C:\Users\marti\Desktop\Discord-Bot-List-master\src\routes\bots\like.js:26:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by TheHellTower** [comment]
> When I enter the /bots/like/ route, and the bot is nsfw, it gives this error:
> 
> ReferenceError: C:\Users\marti\Desktop\Discord-Bot-List-master\src\dynamic\like.ejs:13 11|
> 
> 
> 12| <% if (bot.nsfw) { %>
> > > 13|             <img class="icon nsfw" src=<%= val.logo %> />
> > > 14|           <% } else { %>
> > > 15|             <img class="icon" src=<%= bot.logo %> />
> > > 16|           <% } %>
> 
> val is not defined at eval ("C:\Users\marti\Desktop\Discord-Bot-List-master\src\dynamic\like.ejs":21:26) at like (C:\Users\marti\Desktop\Discord-Bot-List-master\node_modules\ejs\lib\ejs.js:703:17) at tryHandleCache (C:\Users\marti\Desktop\Discord-Bot-List-master\node_modules\ejs\lib\ejs.js:274:36) at exports.renderFile [as engine] (C:\Users\marti\Desktop\Discord-Bot-List-master\node_modules\ejs\lib\ejs.js:491:10) at View.render (C:\Users\marti\Desktop\Discord-Bot-List-master\node_modules\express\lib\view.js:135:8) at tryRender (C:\Users\marti\Desktop\Discord-Bot-List-master\node_modules\express\lib\application.js:657:10) at Function.render (C:\Users\marti\Desktop\Discord-Bot-List-master\node_modules\express\lib\application.js:609:3) at ServerResponse.render (C:\Users\marti\Desktop\Discord-Bot-List-master\node_modules\express\lib\response.js:1039:7) at C:\Users\marti\Desktop\Discord-Bot-List-master\src\routes\bots\like.js:26:9 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Hello, I will look at this right now !

**Comment by BluAimz** [comment]
> > When I enter the /bots/like/ route, and the bot is nsfw, it gives this error:
> > ReferenceError: C:\Users\marti\Desktop\Discord-Bot-List-master\src\dynamic\like.ejs:13 11|
> > 12| <% if (bot.nsfw) { %>
> > > > 13|             <img class="icon nsfw" src=<%= val.logo %> />
> > > > 14|           <% } else { %>
> > > > 15|             <img class="icon" src=<%= bot.logo %> />
> > > > 16|           <% } %>
> > 
> > 
> > val is not defined at eval ("C:\Users\marti\Desktop\Discord-Bot-List-master\src\dynamic\like.ejs":21:26) at like (C:\Users\marti\Desktop\Discord-Bot-List-master\node_modules\ejs\lib\ejs.js:703:17) at tryHandleCache (C:\Users\marti\Desktop\Discord-Bot-List-master\node_modules\ejs\lib\ejs.js:274:36) at exports.renderFile [as engine] (C:\Users\marti\Desktop\Discord-Bot-List-master\node_modules\ejs\lib\ejs.js:491:10) at View.render (C:\Users\marti\Desktop\Discord-Bot-List-master\node_modules\express\lib\view.js:135:8) at tryRender (C:\Users\marti\Desktop\Discord-Bot-List-master\node_modules\express\lib\application.js:657:10) at Function.render (C:\Users\marti\Desktop\Discord-Bot-List-master\node_modules\express\lib\application.js:609:3) at ServerResponse.render (C:\Users\marti\Desktop\Discord-Bot-List-master\node_modules\express\lib\response.js:1039:7) at C:\Users\marti\Desktop\Discord-Bot-List-master\src\routes\bots\like.js:26:9 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
> Hello, I will look at this right now !

**Comment by TheHellTower** [comment]
You are not supposed to close before it get solved !

**Comment by BluAimz** [comment]
> You are not supposed to close before it get solved !


I'm so sorry

**Comment by TheHellTower** [comment]
`val` didn't exist because I'm using `bot`, commited !
